var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.createTemplateTagFirstArg=function(a){return a.raw=a};$jscomp.createTemplateTagFirstArgWithRaw=function(a,b){a.raw=b;return a};$jscomp.arrayIteratorImpl=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}};$jscomp.arrayIterator=function(a){return{next:$jscomp.arrayIteratorImpl(a)}};$jscomp.makeIterator=function(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):$jscomp.arrayIterator(a)};
var showdownConvertor,postYears=new Set,postInYear=new Map;function useShowDown(a){showdownConvertor=a}function getMonthAsName(a){return{"01":"Jan","02":"Feb","03":"Mar","04":"Apr","05":"May","06":"Jun","07":"Jul","08":"Aug","09":"Sep",10:"Oct",11:"Nov",12:"Dec"}[a]}
function readAndProcessTagList(){var a=localStorage.getItem("showTagList"),b,g,k,d,c="";(new Map(JSON.parse(localStorage.getItem("postInYear")))).forEach(function(f,e,h){var m=!1;f.forEach(function(l){l.tags.includes(a)&&(k=l.title,b=e,g=l.month,d=l.day,m||(c=c+'<div><div id="blog-list-year" class="blog-list-year">'+b+'</div><ul class="blog-list-sep-year">',m=!0),c=c+'<li class="blog-list-item">\n                        <a href="../blog/blog-post.html" class="content-link" onclick="(function(){\n                            localStorage[\'year\'] = '+
b+";\n                            localStorage['month'] = "+g+";\n                            localStorage['day'] = "+d+';\n                        })();">\n                            <span id="blog-list-title" class="blog-list-title">'+k+'</span>\n                            <span class="blog-list-date">'+d+" "+getMonthAsName(g)+"</span>\n                        </a>\n                    </li>")});m&&(c+="</ul></div>")});window.addEventListener("load",function(){document.getElementById("blog-title").innerHTML=
a;document.getElementById("blog-content").innerHTML=c})}
function readAndProcessBlogListFile(){if(localStorage.getItem("showTagList"))readAndProcessTagList();else{var a=new XMLHttpRequest;a.onreadystatechange=function(){var b=a.responseText;if(4===a.readyState){b.split("---\n").forEach(function(c){if(""!==c){var f=c.split("; ");c=f[0].split("title: ")[1];var e=f[1].split("date: ")[1],h=$jscomp.makeIterator(e.split("-"));e=h.next().value;var m=h.next().value;h=h.next().value;var l=f[2].replace("\n","").split("tags: ")[1].split(" "),n;f=null==(n=f[3])?void 0:
n.replace("\n","").split("share: ")[1];postYears.add(e);postInYear.has(e)?(n=postInYear.get(e),n.push({title:c,month:m,day:h,tags:l,link:f}),postInYear.set(e,n)):postInYear.set(e,[{title:c,month:m,day:h,tags:l,link:f}])}});htmlContent="";postYears=Array.from(postYears);postYears.sort().reverse();localStorage.setItem("postInYear",JSON.stringify(Array.from(postInYear.entries())));b=$jscomp.makeIterator(postYears);for(var g=b.next();!g.done;g=b.next()){g=g.value;htmlContent=htmlContent+'<div><div id="blog-list-year" class="blog-list-year">'+
g+'</div><ul class="blog-list-sep-year">';var k=postInYear.get(g).sort(function(c,f){var e=new Date,h=new Date;e.setDate(c.day);e.setMonth(c.month);h.setDate(f.day);h.setMonth(f.month);return h-e});k=$jscomp.makeIterator(k);for(var d=k.next();!d.done;d=k.next())d=d.value,htmlContent=htmlContent+'<li class="blog-list-item">\n                        <a href="../blog/blog-post.html" class="content-link" onclick="(function(){\n                            localStorage[\'year\'] = '+g+";\n                            localStorage['month'] = "+
d.month+";\n                            localStorage['day'] = "+d.day+';\n                        })();">\n                             <span id="blog-list-title" class="blog-list-title">'+d.title+'</span>\n                             <span class="blog-list-date">'+d.day+" "+getMonthAsName(d.month)+"</span>\n                         </a>\n                     </li>";htmlContent+="</ul></div>"}document.getElementById("blog-content").innerHTML=htmlContent}};a.open("GET","/layout/blog-list.md",!0);
a.send(null)}};
